### ISSUE TITLE
Parsoid 0.12

### ISSUE THREAD

**Issue by bperel** [thenets/docker-parsoid#16]
Hello,

Parsoid 0.12 was [released ](https://www.mediawiki.org/wiki/Parsoid/Releases#0.12.0_(released_Sep_11,_2020))on September 11th.
Could you create a tag for this version?

Thanks in advance :-)

**Comment by f-ewald** [comment]
I created a pull request against this repo: https://github.com/thenets/docker-parsoid/pull/18

**Comment by thenets** [comment]
@bperel @f-ewald Hi! :) sorry for the big delay.

Version 0.12 is not using NodeJS anymore and doesn't need an external server. The new version is bundled with the Parsoid installation and you can enable it using the `LocalSettings.php` file.

Check the docs:
https://www.mediawiki.org/wiki/Parsoid#Installation

> **Installation**
> In MediaWiki 1.35 LTS Parsoid/PHP is included in the bundle and loaded automatically by Visual Editor. No configuration necessary if used on a single server.
> 
> If you are a developer working on 1.36, explicitly loading Parsoid is required since August 24, 2020 (the auto-load hack was removed in 1.36-wmf.6). Add to LocalSettings.php:
>
> `wfLoadExtension( 'Parsoid', 'vendor/wikimedia/parsoid/extension.json' );`
> This is expected to change for the release of 1.36.

I'll update the README.md file to notify anyone else.
