### ISSUE TITLE
How to use the parser?

### ISSUE THREAD

**Issue by sdabhi23** [thenets/docker-parsoid#5]
There are very clear instructions on how to use the version installed directly on the machine, but how can I use it once I have installed it using docker?

**Comment by thenets** [comment]
Hi @sdabhi23.

The Docker version does nothing but starts the original server so the documentation is the same of the original installation process: https://www.mediawiki.org/wiki/Parsoid

What exactly do you need help?

**Comment by thenets** [comment]
I'll close it. Feel free to comment here if you need help.
