### ISSUE TITLE
Do not overwrite /var/lib/parsoid/config.yaml in /run-parsoid.sh

### ISSUE THREAD

**Issue by sepastian** [thenets/docker-parsoid#7]
Hello,

First, thanks for your work.

I need to change `strictSSL: false` in `/var/lib/parsoid/config.yaml`, and tried to do so by mounting the file as a Docker volume.

Unfortunately, this is not possible, because `/run-parsoid.sh` is overwriting `/var/lib/config.yaml` file during startup.

**Comment by sepastian** [comment]
I managed to get parsoid to work without disabling strict SSL, so this ticket can be closed, thanks anyways.

**Comment by thenets** [comment]
Hi @sepastian :)

I didn't consider that someone wants to change that kind of thing. I can add this feature as a custom ENV during the container deployment.

What do you think?

**Comment by sepastian** [comment]
Hi @thenets :)

I have done that this afternoon, take a look at #8.

**Comment by thenets** [comment]
Oh, perfect! õ/

Thanks a lot. I'll make some tests and merge it to the branch `0.10.x` and maybe to the other versions as well. I'll talk to the core developers and ask what they think about add this to the older versions.

Thanks once again, @sepastian!
